name: Test
on:
  push:
  pull_request:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      - name: Run all tests
        run: yarn test
        env:
          FORCE_COLOR: 2
